In [1]:
import numpy as np
import statsmodels.api as sm
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt
from matplotlib import colors
from matplotlib.ticker import PercentFormatter
import math as m
dat = sm.datasets.get_rdataset("Guerry", "HistData").data

In [2]:
dat.head()

,dept,Region,Department,Crime_pers,Crime_prop,Literacy,Donations,Infants,Suicides,MainCity,...,Crime_parents,Infanticide,Donation_clergy,Lottery,Desertion,Instruction,Prostitutes,Distance,Area,Pop1831
0,1,E,Ain,28870,15890,37,5098,33120,35039,2:Med,...,71,60,69,41,55,46,13,218.372,5762,346.03
1,2,N,Aisne,26226,5521,51,8901,14572,12831,2:Med,...,4,82,36,38,82,24,327,65.945,7369,513.00
2,3,C,Allier,26747,7925,13,10973,17044,114121,2:Med,...,46,42,76,66,16,85,34,161.927,7340,298.26
3,4,E,Basses-Alpes,12935,7289,46,2733,23018,14238,1:Sm,...,70,12,37,80,32,29,2,351.399,6925,155.90
4,5,E,Hautes-Alpes,17488,8174,69,6962,23076,16171,1:Sm,...,22,23,64,79,35,7,1,320.280,5549,129.10

In [5]:
type(dat)

pandas.core.frame.DataFrame

In [7]:
dat.dtypes

dept                 int64
Region              object
Department          object
Crime_pers           int64
Crime_prop           int64
Literacy             int64
Donations            int64
Infants              int64
Suicides             int64
MainCity            object
Wealth               int64
Commerce             int64
Clergy               int64
Crime_parents        int64
Infanticide          int64
Donation_clergy      int64
Lottery              int64
Desertion            int64
Instruction          int64
Prostitutes          int64
Distance           float64
Area                 int64
Pop1831            float64
dtype: object

In [3]:
print(len(dat.dtypes))

23

In [4]:
print(dat['Region'].head())
print(len(dat['Region']))

0    E
1    N
2    C
3    E
4    E
Name: Region, dtype: object
86

In [16]:
dat['Region'].unique()

array(['E', 'N', 'C', 'S', 'W', nan], dtype=object)

In [22]:
print(len(dat['Wealth']))
print(dat['Wealth'].head())

86
0    73
1    22
2    61
3    76
4    83
Name: Wealth, dtype: int64

In [5]:
wealthyDat = dat[dat["Wealth"] > 50]

In [6]:
print(len(wealthyDat))
print(wealthyDat.head())

36
   dept Region    Department  Crime_pers  Crime_prop  Literacy  Donations  \
0     1      E           Ain       28870       15890        37       5098
2     3      C        Allier       26747        7925        13      10973
3     4      E  Basses-Alpes       12935        7289        46       2733
4     5      E  Hautes-Alpes       17488        8174        69       6962
5     7      S       Ardeche        9474       10263        27       3188

   Infants  Suicides MainCity  ...  Crime_parents  Infanticide  \
0    33120     35039    2:Med  ...             71           60
2    17044    114121    2:Med  ...             46           42
3    23018     14238     1:Sm  ...             70           12
4    23076     16171     1:Sm  ...             22           23
5    42117     52547     1:Sm  ...             76           47

   Donation_clergy  Lottery  Desertion  Instruction  Prostitutes  Distance  \
0               69       41         55           46           13   218.372
2               76       66         16           85           34   161.927
3               37       80         32           29            2   351.399
4               64       79         35            7            1   320.280
5               67       70         19           62            1   279.413

   Area  Pop1831
0  5762   346.03
2  7340   298.26
3  6925   155.90
4  5549   129.10
5  5529   340.73

[5 rows x 23 columns]

In [7]:
brokenDat = dat[dat["Wealth"] < 50]

In [8]:
print(len(brokenDat))
print(brokenDat.head())

49
    dept Region        Department  Crime_pers  Crime_prop  Literacy  \
1      2      N             Aisne       26226        5521        51
6      8      N          Ardennes       35203        8847        67
8     10      E              Aube       19602        4086        59
9     11      S              Aude       15647       10431        34
11    13      S  Bouches-du-Rhone       13409        5291        38

    Donations  Infants  Suicides MainCity  ...  Crime_parents  Infanticide  \
1        8901    14572     12831    2:Med  ...              4           82
6        6400    16106     26198    2:Med  ...             53           85
8        3608    18642     10989    2:Med  ...             77           54
9        2582    20225     66498    2:Med  ...             80           35
11       2314     9325      8107     3:Lg  ...             45           74

    Donation_clergy  Lottery  Desertion  Instruction  Prostitutes  Distance  \
1                36       38         82           24          327    65.945
6                49       31         62            9           83   105.694
8                 9       28         86           15          207    83.244
9                27       50         63           48            1   370.949
11               55        3         23           43           25   362.568

    Area  Pop1831
1   7369   513.00
6   5229   289.62
8   6004   246.36
9   6139   270.13
11  5087   359.47

[5 rows x 23 columns]

In [9]:
print(len(dat[dat['Region'] == "E"]))
print(len(dat[dat['Region'] == "N"]))
print(len(dat[dat['Region'] == "C"]))
print(len(dat[dat['Region'] == "S"]))
print(len(dat[dat['Region'] == "W"]))
print(len(dat[dat['Region'] == np.nan]))

17
17
17
17
17
0

In [ ]:

wealthyDat["Region"]
brokenDat["Region"]

In [8]:

results = smf.ols('Lottery ~ Literacy + np.log(Pop1831)', data=dat).fit() #  include both Literacy and log(Pop1831) as separate predictors in the model.
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                Lottery   R-squared:                       0.348
Model:                            OLS   Adj. R-squared:                  0.333
Method:                 Least Squares   F-statistic:                     22.20
Date:                Mon, 24 Aug 2026   Prob (F-statistic):           1.90e-08
Time:                        21:52:32   Log-Likelihood:                -379.82
No. Observations:                  86   AIC:                             765.6
Df Residuals:                      83   BIC:                             773.0
Df Model:                           2
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept         246.4341     35.233      6.995      0.000     176.358     316.510
Literacy           -0.4889      0.128     -3.832      0.000      -0.743      -0.235
np.log(Pop1831)   -31.3114      5.977     -5.239      0.000     -43.199     -19.424
==============================================================================
Omnibus:                        3.713   Durbin-Watson:                   2.019
Prob(Omnibus):                  0.156   Jarque-Bera (JB):                3.394
Skew:                          -0.487   Prob(JB):                        0.183
Kurtosis:                       3.003   Cond. No.                         702.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [38]:
print(len(brokenDat[brokenDat["Wealth"] < 10]))
#print(brokenDat[brokenDat["Wealth"] < 10]["Wealth"])
#print(sorted(brokenDat[brokenDat["Wealth"] < 10]["Wealth"]))

9
11    2
30    8
42    9
44    7
66    6
70    1
71    3
72    4
73    5
Name: Wealth, dtype: int64
[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [39]:
brokenDat[brokenDat["Wealth"] < 10]

,dept,Region,Department,Crime_pers,Crime_prop,Literacy,Donations,Infants,Suicides,MainCity,...,Crime_parents,Infanticide,Donation_clergy,Lottery,Desertion,Instruction,Prostitutes,Distance,Area,Pop1831
11,13,S,Bouches-du-Rhone,13409,5291,38,2314,9325,8107,3:Lg,...,45,74,55,3,23,43,25,362.568,5087,359.47
30,33,W,Gironde,24096,7423,40,5076,10676,19220,3:Lg,...,27,80,48,4,13,41,39,291.624,10000,554.23
42,45,C,Loiret,17722,5042,42,4753,9986,11813,2:Med,...,44,22,16,17,60,37,256,61.106,6775,305.28
44,47,W,Lot-et-Garonne,22969,8943,31,4432,17681,38501,2:Med,...,26,32,46,52,34,50,5,302.345,5361,346.89
66,69,E,Rhone,18793,4504,45,1983,3910,17003,3:Lg,...,37,33,21,2,14,31,104,213.032,3249,434.43
70,75,N,Seine,13945,1368,71,4204,2660,3632,3:Lg,...,60,67,53,1,33,6,4744,0.000,762,935.11
71,76,N,Seine-Inferieure,18355,2906,43,7245,7506,9523,3:Lg,...,28,61,74,9,36,35,546,75.658,6278,693.68
72,77,N,Seine-et-Marne,22201,5786,54,5303,16324,7315,2:Med,...,16,73,26,29,67,37,453,27.647,5915,323.89
73,78,N,Seine-et-Oise,12477,3879,56,4007,16303,3460,2:Med,...,10,30,24,6,42,17,874,16.888,5334,448.18

In [41]:
juke = dat['Region'].unique()

In [43]:
for i in juke:
    print(i)

E
N
C
S
W
nan

In [ ]:
fig, ax = plt.subplots()

ax.bar()

In [ ]:
sum(map(m.fabs, [-x for x in range(-10,11)]))/sum([x for x in range(10,21)])

In [ ]:
sum(map(m.fabs, [-x for x in range(-10,11)]))/sum([-x for x in range(10,21)])

In [ ]:
m.fabs(-22)

In [ ]:
sum(map(m.fabs, [-x for x in range(10,21)]))/sum([x for x in range(10,21)])

In [ ]:
sum(map(m.fabs, [-x for x in range(10,21)]))/sum([-x for x in range(10,21)])

In [ ]:
[x for x in range(0,11)]

In [ ]:
[-x for x in range(0,11)]

In [ ]:
sum(map(m.fabs, [-x for x in range(0,11)]))/sum([x for x in range(0,11)])

In [ ]:
sum(map(m.fabs, [-x for x in range(0,11)]))/sum([-x for x in range(0,11)])

In [ ]:
sum(map(m.fabs, [x for x in range(0,101)]))

In [ ]:
sum(map(m.fabs, [-x for x in range(0,101)]))

## References

+ https://www.statsmodels.org/stable/index.html
+ https://pandas.pydata.org/docs/user_guide/10min.html
+ https://pandas.pydata.org/docs/reference/api/pandas.Series.unique.html
+ https://pandas.pydata.org/docs/reference/api/pandas.Series.kurtosis.html
+ https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.join.html
+ https://pandas.pydata.org/docs/getting_started/intro_tutorials/03_subset_data.html
+ https://pandas.pydata.org/docs/user_guide/indexing.html
+ https://matplotlib.org/stable/gallery/lines_bars_and_markers/bar_colors.html

In [12]:
dir(dat)

['Area',
 'Clergy',
 'Commerce',
 'Crime_parents',
 'Crime_pers',
 'Crime_prop',
 'Department',
 'Desertion',
 'Distance',
 'Donation_clergy',
 'Donations',
 'Infanticide',
 'Infants',
 'Instruction',
 'Literacy',
 'Lottery',
 'MainCity',
 'Pop1831',
 'Prostitutes',
 'Region',
 'Suicides',
 'T',
 'Wealth',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__dataframe_consortium_standard__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_arith_method_with_reindex',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_create_data_for_split_and_tight_to_dict',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_nocopy',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'dept',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']