In [40]:
import numpy as np
import statsmodels.api as sm
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt
from matplotlib import colors
from matplotlib.ticker import PercentFormatter
dat = sm.datasets.get_rdataset("Guerry", "HistData").data

In [3]:
dat.head()

,dept,Region,Department,Crime_pers,Crime_prop,Literacy,Donations,Infants,Suicides,MainCity,...,Crime_parents,Infanticide,Donation_clergy,Lottery,Desertion,Instruction,Prostitutes,Distance,Area,Pop1831
0,1,E,Ain,28870,15890,37,5098,33120,35039,2:Med,...,71,60,69,41,55,46,13,218.372,5762,346.03
1,2,N,Aisne,26226,5521,51,8901,14572,12831,2:Med,...,4,82,36,38,82,24,327,65.945,7369,513.00
2,3,C,Allier,26747,7925,13,10973,17044,114121,2:Med,...,46,42,76,66,16,85,34,161.927,7340,298.26
3,4,E,Basses-Alpes,12935,7289,46,2733,23018,14238,1:Sm,...,70,12,37,80,32,29,2,351.399,6925,155.90
4,5,E,Hautes-Alpes,17488,8174,69,6962,23076,16171,1:Sm,...,22,23,64,79,35,7,1,320.280,5549,129.10

In [5]:
type(dat)

pandas.core.frame.DataFrame

In [7]:
dat.dtypes

dept                 int64
Region              object
Department          object
Crime_pers           int64
Crime_prop           int64
Literacy             int64
Donations            int64
Infants              int64
Suicides             int64
MainCity            object
Wealth               int64
Commerce             int64
Clergy               int64
Crime_parents        int64
Infanticide          int64
Donation_clergy      int64
Lottery              int64
Desertion            int64
Instruction          int64
Prostitutes          int64
Distance           float64
Area                 int64
Pop1831            float64
dtype: object

In [9]:
print(len(dat.dtypes))

23

In [19]:
print(dat['Region'].head())
print(len(dat['Region']))

0    E
1    N
2    C
3    E
4    E
Name: Region, dtype: object
86

In [16]:
dat['Region'].unique()

array(['E', 'N', 'C', 'S', 'W', nan], dtype=object)

In [22]:
print(len(dat['Wealth']))
print(dat['Wealth'].head())

86
0    73
1    22
2    61
3    76
4    83
Name: Wealth, dtype: int64

In [25]:
wealthyDat = dat[dat["Wealth"] > 50]

In [27]:
print(len(wealthyDat))
print(wealthyDat.head())

36
   dept Region    Department  Crime_pers  Crime_prop  Literacy  Donations  \
0     1      E           Ain       28870       15890        37       5098
2     3      C        Allier       26747        7925        13      10973
3     4      E  Basses-Alpes       12935        7289        46       2733
4     5      E  Hautes-Alpes       17488        8174        69       6962
5     7      S       Ardeche        9474       10263        27       3188

   Infants  Suicides MainCity  ...  Crime_parents  Infanticide  \
0    33120     35039    2:Med  ...             71           60
2    17044    114121    2:Med  ...             46           42
3    23018     14238     1:Sm  ...             70           12
4    23076     16171     1:Sm  ...             22           23
5    42117     52547     1:Sm  ...             76           47

   Donation_clergy  Lottery  Desertion  Instruction  Prostitutes  Distance  \
0               69       41         55           46           13   218.372
2               76       66         16           85           34   161.927
3               37       80         32           29            2   351.399
4               64       79         35            7            1   320.280
5               67       70         19           62            1   279.413

   Area  Pop1831
0  5762   346.03
2  7340   298.26
3  6925   155.90
4  5549   129.10
5  5529   340.73

[5 rows x 23 columns]

In [28]:
brokenDat = dat[dat["Wealth"] < 50]

In [29]:
print(len(brokenDat))
print(brokenDat.head())

49
    dept Region        Department  Crime_pers  Crime_prop  Literacy  \
1      2      N             Aisne       26226        5521        51
6      8      N          Ardennes       35203        8847        67
8     10      E              Aube       19602        4086        59
9     11      S              Aude       15647       10431        34
11    13      S  Bouches-du-Rhone       13409        5291        38

    Donations  Infants  Suicides MainCity  ...  Crime_parents  Infanticide  \
1        8901    14572     12831    2:Med  ...              4           82
6        6400    16106     26198    2:Med  ...             53           85
8        3608    18642     10989    2:Med  ...             77           54
9        2582    20225     66498    2:Med  ...             80           35
11       2314     9325      8107     3:Lg  ...             45           74

    Donation_clergy  Lottery  Desertion  Instruction  Prostitutes  Distance  \
1                36       38         82           24          327    65.945
6                49       31         62            9           83   105.694
8                 9       28         86           15          207    83.244
9                27       50         63           48            1   370.949
11               55        3         23           43           25   362.568

    Area  Pop1831
1   7369   513.00
6   5229   289.62
8   6004   246.36
9   6139   270.13
11  5087   359.47

[5 rows x 23 columns]

In [17]:
print(len(dat[dat['Region'] == "E"]))
print(len(dat[dat['Region'] == "N"]))
print(len(dat[dat['Region'] == "C"]))
print(len(dat[dat['Region'] == "S"]))
print(len(dat[dat['Region'] == "W"]))
print(len(dat[dat['Region'] == np.nan]))

17
17
17
17
17
0

In [ ]:

wealthyDat["Region"]
brokenDat["Region"]

In [8]:

results = smf.ols('Lottery ~ Literacy + np.log(Pop1831)', data=dat).fit() #  include both Literacy and log(Pop1831) as separate predictors in the model.
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                Lottery   R-squared:                       0.348
Model:                            OLS   Adj. R-squared:                  0.333
Method:                 Least Squares   F-statistic:                     22.20
Date:                Mon, 24 Aug 2026   Prob (F-statistic):           1.90e-08
Time:                        21:52:32   Log-Likelihood:                -379.82
No. Observations:                  86   AIC:                             765.6
Df Residuals:                      83   BIC:                             773.0
Df Model:                           2
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept         246.4341     35.233      6.995      0.000     176.358     316.510
Literacy           -0.4889      0.128     -3.832      0.000      -0.743      -0.235
np.log(Pop1831)   -31.3114      5.977     -5.239      0.000     -43.199     -19.424
==============================================================================
Omnibus:                        3.713   Durbin-Watson:                   2.019
Prob(Omnibus):                  0.156   Jarque-Bera (JB):                3.394
Skew:                          -0.487   Prob(JB):                        0.183
Kurtosis:                       3.003   Cond. No.                         702.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [38]:
print(len(brokenDat[brokenDat["Wealth"] < 10]))
#print(brokenDat[brokenDat["Wealth"] < 10]["Wealth"])
#print(sorted(brokenDat[brokenDat["Wealth"] < 10]["Wealth"]))

9
11    2
30    8
42    9
44    7
66    6
70    1
71    3
72    4
73    5
Name: Wealth, dtype: int64
[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [39]:
brokenDat[brokenDat["Wealth"] < 10]

,dept,Region,Department,Crime_pers,Crime_prop,Literacy,Donations,Infants,Suicides,MainCity,...,Crime_parents,Infanticide,Donation_clergy,Lottery,Desertion,Instruction,Prostitutes,Distance,Area,Pop1831
11,13,S,Bouches-du-Rhone,13409,5291,38,2314,9325,8107,3:Lg,...,45,74,55,3,23,43,25,362.568,5087,359.47
30,33,W,Gironde,24096,7423,40,5076,10676,19220,3:Lg,...,27,80,48,4,13,41,39,291.624,10000,554.23
42,45,C,Loiret,17722,5042,42,4753,9986,11813,2:Med,...,44,22,16,17,60,37,256,61.106,6775,305.28
44,47,W,Lot-et-Garonne,22969,8943,31,4432,17681,38501,2:Med,...,26,32,46,52,34,50,5,302.345,5361,346.89
66,69,E,Rhone,18793,4504,45,1983,3910,17003,3:Lg,...,37,33,21,2,14,31,104,213.032,3249,434.43
70,75,N,Seine,13945,1368,71,4204,2660,3632,3:Lg,...,60,67,53,1,33,6,4744,0.000,762,935.11
71,76,N,Seine-Inferieure,18355,2906,43,7245,7506,9523,3:Lg,...,28,61,74,9,36,35,546,75.658,6278,693.68
72,77,N,Seine-et-Marne,22201,5786,54,5303,16324,7315,2:Med,...,16,73,26,29,67,37,453,27.647,5915,323.89
73,78,N,Seine-et-Oise,12477,3879,56,4007,16303,3460,2:Med,...,10,30,24,6,42,17,874,16.888,5334,448.18

In [41]:
juke = dat['Region'].unique()

In [43]:
for i in juke:
    print(i)

E
N
C
S
W
nan

In [ ]:
fig, ax = plt.subplots()

ax.bar()

## References

+ https://www.statsmodels.org/stable/index.html
+ https://pandas.pydata.org/docs/user_guide/10min.html
+ https://pandas.pydata.org/docs/reference/api/pandas.Series.unique.html
+ https://pandas.pydata.org/docs/reference/api/pandas.Series.kurtosis.html
+ https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.join.html
+ https://pandas.pydata.org/docs/getting_started/intro_tutorials/03_subset_data.html
+ https://pandas.pydata.org/docs/user_guide/indexing.html
+ https://matplotlib.org/stable/gallery/lines_bars_and_markers/bar_colors.html